query fetchUserByID($id: ID!) {
  user(id: $id) {
    id
    login
    displayName
    description
    createdAt
    profileImageURL(width: 70){}
    roles {
      isPartner
    }
    stream {
      id
      title
      type
      viewersCount
      createdAt
      previewImageURL
      game {
        id
        displayName
        avatarURL
        description
        followersCount
      }
    }
  }
}
